---
api:
  host: 'HOSTNAME'
  port: 'SERVICE_PORT'
  apiKeyHash: 'API_KEY_HASH'
database:
  host: 'POSTGRES_HOST'
  port: 'POSTGRES_PORT'
  user: 'POSTGRES_USER'
  password: 'POSTGRES_PASSWORD'
  name: 'POSTGRES_DB'
p2p:
  host: 'P2P_HOST'
  port: 'P2P_PORT'
guard:
  mnemonic: 'MNEMONIC'
tss:
  secret: 'TSS_SECRET'
cardano:
  koios:
    authToken: 'KOIOS_AUTH_TOKEN'
  blockfrost:
    projectId: 'BLOCKFROST_PROJECT_ID'
ethereum:
  rpc:
    authToken: 'ETHEREUM_RPC_AUTH_TOKEN'
binance:
  rpc:
    authToken: 'BINANCE_RPC_AUTH_TOKEN'
doge:
  rpc:
    username: 'DOGE_RPC_USERNAME'
    password: 'DOGE_RPC_PASSWORD'
    apiKey: 'DOGE_RPC_API_KEY'
bitcoinRunes:
  rpc:
    username: 'BITCOIN_RUNES_RPC_USERNAME'
    password: 'BITCOIN_RUNES_RPC_PASSWORD'
    apiKey: 'BITCOIN_RUNES_RPC_API_KEY'
  unisat:
    apiKey: 'BITCOIN_RUNES_UNISAT_API_KEY'
overrideLokiBasicAuth: 'OVERRIDE_LOKI_BASIC_AUTH'
discordWebHookUrl: 'DISCORD_WEBHOOK_URL'
